// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ACOwXVYmbSSDHFJVvPHAnjdXnY0SCPs',
    appId: '1:529646124371:web:980a46c7eb7545c12fb5a6',
    messagingSenderId: '529646124371',
    projectId: 'family-circle-a81cf',
    authDomain: 'family-circle-a81cf.firebaseapp.com',
    databaseURL: 'https://family-circle-a81cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-circle-a81cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxiiHnDUEXYpJUNCbhc2pbKBEYPwlIsk',
    appId: '1:529646124371:android:e63900e86b36c81f2fb5a6',
    messagingSenderId: '529646124371',
    projectId: 'family-circle-a81cf',
    databaseURL: 'https://family-circle-a81cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-circle-a81cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtm40ujz6CXkSc0ffktGdbJH4pvFzPqx4',
    appId: '1:529646124371:ios:f3bb1824e62ef9322fb5a6',
    messagingSenderId: '529646124371',
    projectId: 'family-circle-a81cf',
    databaseURL: 'https://family-circle-a81cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-circle-a81cf.firebasestorage.app',
    iosClientId: '529646124371-brl1jg1d1qjmsogs868l3opaa6gdig2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyCircle',
  );
}
